### PR TITLE
Add cairo post v1.17.4 patches

### PR DESCRIPTION
**Pull request by donny-dont**
There is no ETA for a post 1.17.4 release as the planned releases have all slipped. Because of this cherry pick security patches.

### CODE REVIEW

**Comment by donny-dont** [comment]
The patches don't have any identifiers in them to go back to the original commit. You can just look through https://gitlab.freedesktop.org/cairo/cairo/-/commits/master/ for the corresponding commits.

**Comment by donny-dont** [comment]
@tomoki can you see if there’s anything else to add?

A smoke test with the patches applied worked fine in a WinCairo build

**Comment by tomoki** [comment]
Thanks for the PR!
I look over the merge requests in cairo gitlab which were merged after `1.17.4` (2020/11/29), and the security fixes related to WinCairo I found are included in this PR. (Others are related to pdf, quartz, recording surfaces etc which are not used in WinCairo)

**Review by tomoki — APPROVED** [review]
LGTM 👍

**Pull request merged**
