### PR TITLE
Remove openjpeg port

### PR DESCRIPTION
**Pull request by donny-dont**
JPEG 2000 files aren't really used so remove support.

### CODE REVIEW

**Comment by fujii** [comment]
Windows WebKit is using it. https://github.com/WebKit/WebKit/blob/2a7c1bfb98af1ae64e9dc59d5db8b7befc8f23d4/Source/cmake/OptionsWin.cmake#L94

**Comment by donny-dont** [comment]
Its optional. The CMake looks for it and if it finds it it sets `USE_OPENJPEG`. So if someone wants to include it they can add the built files and WebKit will build with it.

```cmake
find_package(OpenJPEG 2.3.1)
if (OpenJPEG_FOUND)
    SET_AND_EXPOSE_TO_BUILD(USE_OPENJPEG ON)
endif ()
```

**Comment by fujii** [comment]
Some web sites serves JPEG 2000 for WebKit based browsers.
Safari is still supporting it. https://caniuse.com/jpeg2000
https://bugs.webkit.org/show_bug.cgi?id=178758
https://bugs.webkit.org/show_bug.cgi?id=186272

**Comment by fujii** [comment]
You can check it at https://web-saku.net/new-image-formats/

**Comment by donny-dont** [comment]
Were not shipping a Windows browser and don't enable it on PlayStation so I don't think we should continue supporting it.

**Review by fujii — APPROVED** [review]

**Pull request merged**
